export const CHANGE_MESSAGE_BOX = "CHANGE_MESSAGE_BOX";
export const SEND_MESSAGE_TO_SERVER = "SEND_MESSAGE_TO_SERVER";
export const SET_RESPONSE_MESSAGE = "SET_RESPONSE_MESSAGE";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";