export const CHANGE_MESSAGE_BOX = "CHANGE_MESSAGE_BOX";
export const SEND_MESSAGE_TO_SERVER = "SEND_MESSAGE_TO_SERVER";
export const SET_RESPONSE_MESSAGE = "SET_RESPONSE_MESSAGE";
export const SET_USER_SESSION_ID = "SET_USER_SESSION_ID";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_ENABLE_BOT_SPEECH = "SET_ENABLE_BOT_SPEECH";
export const SET_ENABLE_MIC_INPUT = "SET_ENABLE_MIC_INPUT";